### ISSUE TITLE
[Categorize] Math editor doesn't display properly

### ISSUE THREAD

**Issue by alex-alberto** [pie-framework/pie-elements#53] opened 2018-08-01 17:15 UTC
When Editing/Adding a choice label, and trying to add a math equation, the math editor doesn't properly show up.

![ijceblidiknkipbd](https://user-images.githubusercontent.com/36770983/43537298-efdeeed6-958c-11e8-9fd6-44e99cd824ea.png)

Tested on http://sbox.powermylearning.org/piedemo/Category_Example.html

@edeustace @elodszopos @narayankj

**Comment by elodszopos** [comment] 2018-08-02 11:07
Duplicate of #52

**Closed by elodszopos** 2018-08-02 11:07 UTC
